spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: ""
    password: ""